language: java
install: true

jdk:
  - oraclejdk8

script:
  - ./mvnw install

notifications:
  slack:
    rooms:
      - codingnomads2019:d1aWT8GvnxhOMXgNmiIHV0eJ#java-travis
    on_success: always
    on_failure: always